# -*- coding: utf-8 -*-
"""ML_Project2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZJSjZyX1FLAdHfeZ06ywMxVK7NLJoD_
"""

import pandas as pd
from sklearn.metrics.pairwise import cosine_similarity

data = {
    'movie':['Avatar','Titanic','Avengers','Batman','Iron Man'],
    'User1':[5,4,5,2,5],
    'User2':[4,5,4,1,4],
    'User3':[5,4,5,2,5],
}

df = pd.DataFrame(data)
print(df)

movie_matrix = df.set_index('movie')
print(movie_matrix)

similarity = cosine_similarity(movie_matrix)
similarity_df = pd.DataFrame(similarity,index=movie_matrix.index,columns=movie_matrix.index)
print(similarity_df)

def recommend(movie_name):
  similar_movie = similarity_df[movie_name]
  similar_movie = similar_movie.sort_values(ascending=False)
  return similar_movie[1:4]

print(recommend('Avatar'))

